version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64
  - MinGW

install:
- cmd: >-
    pip install openpyxl --user

    pip install chardet --user

    msiexec /i externals\cppcheck\cppcheck-1.84-x64-Setup.msi /quiet /qn /norestart /log cppcheck-install.log

build_script:
- cmd: >-
    call checkEncoding.bat

    call build-by-cmake_with_ninja.bat %PLATFORM% %CONFIGURATION%

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'
