version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64
  - MinGW

install:
- cmd: >-
    pip install openpyxl --user

    pip install chardet --user

    msiexec /i externals\cppcheck\cppcheck-1.84-x64-Setup.msi /quiet /qn /norestart /log cppcheck-install.log

    @rem externals\doxygen\doxygen-1.8.14-setup.exe /silent /suppressmsgboxes
    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-gtest"
    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm doxygen"

build_script:
- cmd: >-
    call checkEncoding.bat

    call build-all.bat %PLATFORM% %CONFIGURATION%

    echo call build-by-cmake.bat %PLATFORM% %CONFIGURATION%
         call build-by-cmake.bat %PLATFORM% %CONFIGURATION%

    call tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'
