name: build sakura

on:
  push:
    paths-ignore:
      - '**.md'
      - .gitignore
      - .editorconfig
      - 'ci/**'
      - '*.yml'

  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
      - .editorconfig
      - 'ci/**'
      - '*.yml'

defaults:
  run:
    shell: powershell

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    name: CheckEncoding
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: CheckEncoding
      run: |
        pip install chardet --user
        py checkEncoding.py

  build:
    # The type of runner that the job will run on
    name: MSBuild
    needs: check
    runs-on: windows-latest

    strategy:
      matrix:
        platform:
          - Win32
          - x64
        config:
          - Debug
          - Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    ## see https://github.com/actions/checkout
    - uses: actions/checkout@v2

    ## see https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild
      run: build-sln.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    - name: Run Tests
      run: ${{ matrix.platform }}\${{ matrix.config }}\tests1.exe
        --gtest_output=xml:tests1-googletest-${{ matrix.platform }}-${{ matrix.config }}.xml

    - name: Upload Bin
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v2
      with:
        name: sakura-Bin-${{ matrix.platform }}
        path: |
          ${{ matrix.platform }}\${{ matrix.config }}\sakura.exe
          ${{ matrix.platform }}\${{ matrix.config }}\sakura_lang_en_US.dll

  buildChm:
    name: BuildChm
    needs: check
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Locale Emulator
      run: choco install locale-emulator -y

    - name: Build HTML Help
      shell: cmd
      run: build-chm.bat

    - name: Copy Outputs
      run: |
        Copy-Item help\macro\macro.chm   help\
        Copy-Item help\plugin\plugin.chm help\
        Copy-Item help\sakura\sakura.chm help\

    - name: Upload HTML Help
      uses: actions/upload-artifact@v2
      with:
        name: sakura-Chm
        path: |
          help\macro.chm
          help\plugin.chm
          help\sakura.chm
