name: build sakura

on:
  push:
    paths-ignore:
      - '**.md'
      - .gitignore
      - .editorconfig
      - 'ci/**'
      - '*.yml'

  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
      - .editorconfig
      - 'ci/**'
      - '*.yml'

defaults:
  run:
    shell: powershell

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    name: CheckEncoding
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: CheckEncoding
      run: |
        pip install chardet --user
        py checkEncoding.py

  build:
    # The type of runner that the job will run on
    name: MSBuild
    needs: check
    runs-on: windows-latest

    strategy:
      matrix:
        platform:
          - Win32
          - x64
        config:
          - Debug
          - Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    ## see https://github.com/actions/checkout
    - uses: actions/checkout@v2

    ## see https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild
      run: build-sln.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    - name: Run Tests
      run: ${{ matrix.platform }}\${{ matrix.config }}\tests1.exe
        --gtest_output=xml:tests1-googletest-${{ matrix.platform }}-${{ matrix.config }}.xml

    - name: Upload Bin
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v2
      with:
        name: sakura-Bin-${{ matrix.platform }}
        path: |
          ${{ matrix.platform }}\${{ matrix.config }}\sakura.exe
          ${{ matrix.platform }}\${{ matrix.config }}\sakura_lang_en_US.dll

  buildChm:
    name: BuildChm
    needs: check
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Locale Emulator
      run: choco install locale-emulator -y

    - name: Build HTML Help
      shell: cmd
      run: build-chm.bat

    - name: Copy Outputs
      run: |
        Copy-Item help\macro\macro.chm   help\
        Copy-Item help\plugin\plugin.chm help\
        Copy-Item help\sakura\sakura.chm help\

    - name: Upload HTML Help
      uses: actions/upload-artifact@v2
      with:
        name: sakura-Chm
        path: |
          help\macro.chm
          help\plugin.chm
          help\sakura.chm

  mingw:
    name: Build with MinGW
    needs: check
    runs-on: windows-latest

    strategy:
      matrix:
        platform:
          - MinGW
        config:
          - Debug
          - Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    ## see https://github.com/actions/checkout
    - uses: actions/checkout@v2

    - name: install MinGW-w64-gtest
      run: C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-gtest"

    - name: Run Batch File
      run: tests\build-and-test.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    - name: Upload MinGW
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v2
      with:
        name: sakura-MinGW-Bin
        path: sakura_core\sakura.exe

  package:
    name: BuildInstaller
    needs: [build, buildChm, mingw]
    runs-on: windows-latest

    strategy:
      matrix:
        platform:
          - Win32
          - x64
        config:
          - Release

    steps:
    - uses: actions/checkout@v2

    - name: Create Installer work directory
      run: |
        Move-Item -Path installer\sinst_src -Destination installer\sakura
        New-Item -Path installer\bregonig -ItemType Directory
        New-Item -Path installer\ctags    -ItemType Directory
        New-Item -Path installer\sakura\license\bregonig -ItemType Directory
        New-Item -Path installer\sakura\license\ctags    -ItemType Directory
        7z x -oinstaller\bregonig installer\externals\bregonig\bron420.zip
        Move-Item -Path installer\bregonig\*.txt -Destination installer\sakura\license\bregonig\
        Move-Item -Path LICENSE -Destination installer\sakura\license\LICENSE

    - name: Prepare install stuff for x86
      if: ${{ matrix.platform == 'Win32' }}
      run: |
        Move-Item -Path installer\bregonig\*.dll -Destination installer\sakura\
        7z x -oinstaller\ctags installer\externals\universal-ctags\ctags-2020-01-12_feffe43a-x86.zip
        Move-Item -Path installer\ctags\license\* -Destination installer\sakura\license\ctags\
        Move-Item -Path installer\ctags\ctags.exe -Destination installer\sakura\

    - name: Prepare install stuff for x64
      if: ${{ matrix.platform == 'x64' }}
      run: |
        Move-Item -Path installer\bregonig\x64\*.dll -Destination installer\sakura\
        7z x -oinstaller\ctags installer\externals\universal-ctags\ctags-2020-01-12_feffe43a-x64.zip
        Move-Item -Path installer\ctags\license\* -Destination installer\sakura\license\ctags\
        Move-Item -Path installer\ctags\ctags.exe -Destination installer\sakura\

    - name: Download Bin
      uses: actions/download-artifact@v2
      with:
        name: sakura-Bin-${{ matrix.platform }}
        path: installer\sakura\

    - name: Download HTML Help
      uses: actions/download-artifact@v2
      with:
        name: sakura-Chm
        path: installer\sakura\

    - name: 'Build Installer'
      run: ISCC.exe installer\sakura-${{ matrix.platform }}.iss

    - name: Upload Installer for Preview
      if: ${{ matrix.platform == 'x64' }}
      uses: actions/upload-artifact@v2
      with:
        name: sakura-installer-x64
        path: installer\Output-x64\*.exe

    - name: Upload Installer
      if: ${{ matrix.platform == 'Win32' }}
      uses: actions/upload-artifact@v2
      with:
        name: sakura-installer-x86
        path: installer\Output-Win32\*.exe
